#!/usr/bin/env python3
"""Stage 4: add a rendered forecast to the static site and push it.

    python publish.py ./NVDA-bundle --html NVDA-forecast.html

Reads the metadata out of the bundle and the analysis — never out of the
rendered HTML — copies the page into the site, rebuilds the index, commits and
pushes. Re-running for the same ticker and date replaces that entry rather than
duplicating it, so a corrected forecast is a re-publish, not a cleanup job.

The index is written with its data inlined rather than fetched: a fetch() of
data/forecasts.json is blocked by CORS on file://, which would leave the table
mysteriously empty whenever the site is opened straight from disk.
"""

from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

DEFAULT_REPO = Path(os.environ.get("FORECAST_SITE",
                                   Path.home() / "Desktop" / "stock-forecasts"))

BACK_LINK = (
    '<div style="max-width:1080px;margin:0 auto 14px;font:14px/1.6 system-ui,'
    '-apple-system,\'Segoe UI\',sans-serif">'
    '<a href="../index.html" style="color:var(--series-1,#2a78d6);'
    'text-decoration:none;font-weight:600">&larr; All forecasts</a></div>'
)


# --------------------------------------------------------------------------
# Metadata
# --------------------------------------------------------------------------

def snapshot_num(snapshot, key):
    cell = (snapshot or {}).get(key)
    if not isinstance(cell, dict):
        return None
    if cell.get("num") is not None:
        return float(cell["num"])
    import re
    m = re.search(r"-?\d+(?:\.\d+)?", str(cell.get("value") or ""))
    return float(m.group(0)) if m else None


def composite(scorecard):
    weight = sum(float(r.get("weight") or 0) for r in scorecard or [])
    if not weight:
        return None
    return round(sum(float(r["score"]) * float(r.get("weight") or 0)
                     for r in scorecard) / weight, 3)


def first_sentence(text, limit=240):
    body = " ".join(str(text or "").replace("**", "").split())
    if not body:
        return ""
    cut = body.find(". ")
    out = body if cut < 0 else body[:cut + 1]
    return out if len(out) <= limit else out[:limit - 1].rstrip() + "…"


def extract(bundle, analysis, date_override=None):
    meta = bundle.get("meta") or {}
    snapshot = (bundle.get("finviz") or {}).get("snapshot") or {}
    profile = bundle.get("profile") or {}
    target = analysis.get("target_price") or {}

    price = snapshot_num(snapshot, "Price")
    target_value = target.get("value")
    try:
        target_value = float(target_value) if target_value is not None else None
    except (TypeError, ValueError):
        target_value = None

    collected = str(meta.get("collected_at") or "")[:10]
    date = date_override or (collected if len(collected) == 10
                             else dt.date.today().isoformat())

    unavailable = [r.get("dimension") for r in (analysis.get("scorecard") or [])
                   if r.get("unavailable")]

    return {
        "ticker": meta.get("ticker"),
        "name": meta.get("name") or profile.get("name"),
        "sector": profile.get("sector"),
        "date": date,
        "price": round(price, 2) if price is not None else None,
        "target": round(target_value, 2) if target_value is not None else None,
        "upside_pct": (round((target_value / price - 1) * 100, 1)
                       if price and target_value else None),
        "rating": str(analysis.get("rating") or "").upper(),
        "conviction": str(analysis.get("conviction") or "").lower(),
        "composite": composite(analysis.get("scorecard")),
        "horizon": target.get("horizon"),
        "next_report": (bundle.get("resolved") or {}).get("next_report_date"),
        "depth": meta.get("depth"),
        "unavailable": unavailable,
        "summary": first_sentence(analysis.get("thesis")),
        "path": None,  # filled in by the caller
    }


# --------------------------------------------------------------------------
# Index page
# --------------------------------------------------------------------------

INDEX_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Stock forecasts</title>
<link rel="stylesheet" href="assets/site.css">
</head><body><div class="wrap">

<header class="top">
  <h1>Stock forecasts</h1>
  <p class="tagline">Every projection generated by the <code>stock-forecast</code>
    skill. Search by symbol, sector or company; click through for the full
    workup.</p>
</header>

<div class="bar">
  <input id="q" type="search" placeholder="Search symbol, company or sector…"
         autocomplete="off" spellcheck="false" aria-label="Search forecasts">
  <div class="chips" role="group" aria-label="Filter by rating">
    <button class="chip" data-filter="all" aria-pressed="true">All</button>
    <button class="chip" data-filter="buy" aria-pressed="false">Buy</button>
    <button class="chip" data-filter="sell" aria-pressed="false">Sell</button>
  </div>
  <span class="count" id="count"></span>
</div>

<div class="card">
<table>
  <thead><tr>
    <th data-key="ticker">Symbol<span class="arrow"></span></th>
    <th data-key="date" class="n">Date<span class="arrow">▼</span></th>
    <th data-key="rating">Call<span class="arrow"></span></th>
    <th data-key="price" class="n">Price then<span class="arrow"></span></th>
    <th data-key="target" class="n">Target<span class="arrow"></span></th>
    <th data-key="upside_pct" class="n">Implied<span class="arrow"></span></th>
    <th data-key="composite" class="n hide-sm">Score<span class="arrow"></span></th>
    <th class="n"></th>
  </tr></thead>
  <tbody id="rows"></tbody>
</table>
</div>

<footer>
  {count} forecast{plural} · last updated {generated}<br>
  &ldquo;Price then&rdquo; is the price on the day the forecast was made, not today.
  These are forecasts built from public information — not predictions, and not
  investment advice.
</footer>

</div>
<script>window.FORECASTS = {payload};</script>
<script src="assets/site.js"></script>
</body></html>
"""


def write_index(repo, manifest):
    rows = manifest["forecasts"]
    text = (INDEX_TEMPLATE
            .replace("{payload}", json.dumps(rows, ensure_ascii=False))
            .replace("{count}", str(len(rows)))
            .replace("{plural}", "" if len(rows) == 1 else "s")
            .replace("{generated}", html.escape(manifest.get("generated") or "—")))
    (repo / "index.html").write_text(text, encoding="utf-8")


def inject_back_link(source, destination):
    """Copy the forecast page in, adding a link back to the index."""
    text = Path(source).read_text(encoding="utf-8")
    anchor = '<div class="wrap">'
    if anchor in text and "All forecasts" not in text:
        text = text.replace(anchor, anchor + BACK_LINK, 1)
    Path(destination).write_text(text, encoding="utf-8")


# --------------------------------------------------------------------------
# Git
# --------------------------------------------------------------------------

def git(repo, *args, check=True):
    proc = subprocess.run(["git", "-C", str(repo), *args],
                          capture_output=True, text=True,
                          encoding="utf-8", errors="replace")
    if check and proc.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} failed:\n"
                         f"{(proc.stderr or proc.stdout).strip()}")
    return proc.stdout.strip()


def has_remote(repo):
    return bool(git(repo, "remote", check=False))


# --------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="publish.py",
        description="Add a rendered forecast to the static site and push it.")
    parser.add_argument("bundle_dir", help="the bundle directory for this forecast")
    parser.add_argument("--html", help="rendered page (default TICKER-forecast.html)")
    parser.add_argument("--repo", default=str(DEFAULT_REPO),
                        help=f"site repo (default {DEFAULT_REPO})")
    parser.add_argument("--date", help="override the forecast date (YYYY-MM-DD)")
    parser.add_argument("--no-push", action="store_true",
                        help="commit but do not push")
    parser.add_argument("--no-commit", action="store_true",
                        help="write the files only; leave git alone")
    args = parser.parse_args(argv)

    repo = Path(args.repo)
    if not (repo / "assets" / "site.css").exists():
        raise SystemExit(f"{repo} does not look like the forecast site "
                         "(assets/site.css missing). Pass --repo or set "
                         "FORECAST_SITE.")

    folder = Path(args.bundle_dir)
    bundle_path, analysis_path = folder / "bundle.json", folder / "analysis.json"
    for path in (bundle_path, analysis_path):
        if not path.exists():
            raise SystemExit(f"missing {path}. Run collect.py, write the analysis, "
                             "then render before publishing.")

    bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    analysis = json.loads(analysis_path.read_text(encoding="utf-8"))
    entry = extract(bundle, analysis, args.date)

    if not entry["ticker"]:
        raise SystemExit("bundle has no ticker in meta")
    if entry["rating"] not in ("BUY", "SELL"):
        raise SystemExit(f"rating must be BUY or SELL, got '{entry['rating']}'")

    source = Path(args.html) if args.html else Path(f"{entry['ticker']}-forecast.html")
    if not source.exists():
        raise SystemExit(f"rendered page not found: {source}\n"
                         "Pass --html, or run render.py first.")

    filename = f"{entry['ticker']}-{entry['date']}.html"
    entry["path"] = f"forecasts/{filename}"
    inject_back_link(source, repo / "forecasts" / filename)

    manifest_path = repo / "data" / "forecasts.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        manifest = {"forecasts": []}
    rows = [r for r in manifest.get("forecasts", [])
            if not (r.get("ticker") == entry["ticker"] and r.get("date") == entry["date"])]
    replaced = len(rows) != len(manifest.get("forecasts", []))
    rows.append(entry)
    rows.sort(key=lambda r: (r.get("date") or "", r.get("ticker") or ""), reverse=True)

    manifest = {
        "generated": dt.datetime.now().strftime("%Y-%m-%d %H:%M"),
        "count": len(rows),
        "forecasts": rows,
    }
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False),
                             encoding="utf-8")
    write_index(repo, manifest)

    action = "updated" if replaced else "added"
    print(f"{action} {entry['ticker']} {entry['date']} — {entry['rating']} "
          f"(price {entry['price']}, target {entry['target']}) -> {entry['path']}",
          file=sys.stderr)
    print(f"index rebuilt with {len(rows)} forecast(s)", file=sys.stderr)

    if args.no_commit:
        return 0

    if not (repo / ".git").exists():
        print("note: not a git repo yet — files written, nothing committed",
              file=sys.stderr)
        return 0

    git(repo, "add", "index.html", "data/forecasts.json", f"forecasts/{filename}")
    if not git(repo, "status", "--porcelain", check=False):
        print("nothing changed; no commit made", file=sys.stderr)
        return 0

    verb = "Update" if replaced else "Add"
    message = (f"{verb} {entry['ticker']} forecast {entry['date']} — "
               f"{entry['rating']}, target ${entry['target']}")
    git(repo, "commit", "-m", message)
    print(f"committed: {message}", file=sys.stderr)

    if args.no_push:
        print("--no-push set; not pushing", file=sys.stderr)
        return 0
    if not has_remote(repo):
        print("no git remote configured; commit is local only", file=sys.stderr)
        return 0

    branch = git(repo, "rev-parse", "--abbrev-ref", "HEAD")
    git(repo, "push", "origin", branch)
    print(f"pushed to origin/{branch}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
